image:
  repository: registry.cn-hangzhou.aliyuncs.com/acs/kube2ram
  tag: 1.0.0
  pullPolicy: IfNotPresent

securityContext:
  privileged: true

resources:
  requests:
    cpu: 10m
    memory: 10Mi

hostInterface: cni0
